/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import elementos.Asignatura;
import elementos.Curso;
import java.util.ArrayList;
import java.util.TreeSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class CrearCurso extends JFrame {

    /**
     * Constructor primario
     */
    public CrearCurso() {
        initComponents();
    }

    /**
     * Constructor crear curso
     *
     * @param ventanaPadre
     */
    public CrearCurso(Principal ventanaPadre) {
        this.padre = ventanaPadre;
        initComponents();
    }

    /**
     * Constructor modificar curso
     *
     * @param ventanaPadre
     * @param curso Objeto curso el cual se quiere modificar
     */
    public CrearCurso(Principal ventanaPadre, Curso curso) {
        initComponents();
        this.padre = ventanaPadre;
        this.rellenarCampos(curso);
        this.moverLisAsig(0);
        jButton5.setEnabled(true);
        jButton4.setEnabled(true);
        jButton2.setText("Modificar");
        this.modificar = true;
    }

    /**
     * Metodo que envia el curso creado a la ventana padre
     */
    private void enviarCurso() {
        padre.crearCurso(getCurso(), modificar);

    }

    /**
     * Añadir asignatura creada en la ventana hija o modifica la asignatura
     * enviada a la ventana hija segun el parametro m
     *
     * @param a
     * @param m indica si la ventana hija fue instanciada en modo modificacion
     */
    public void addAsignatura(Asignatura a, boolean m) {
        if (m) {
            ArrayList<Asignatura> cop = new ArrayList(asignatura);
            asignatura.remove(cop.get(punteroAsig));
            this.asignatura.add(a);
            this.refrescarLista();
        } else {
            this.asignatura.add(a);
            this.moverLisAsig(1);
        }
        jButton5.setEnabled(true);
        jButton4.setEnabled(true);
    }

    public Curso getCurso() {
        Curso r = new Curso(cursoTex.getText());
        r.setAsignatura(asignatura);
        return r;
    }

    /**
     * Metodo que rellena los campos con los datos del parametro cur
     *
     * @param cur Objeto Curso
     */
    private void rellenarCampos(Curso cur) {
        this.asignatura = cur.getAsignatura();
        this.cursoTex.setText(cur.getNombre());
        this.punteroAsig = 0;
        this.refrescarLista();
    }

    /**
     * Recorer la lista en infinito
     *
     * @param i las posiciones que se debe correr public void moverLisAsig(int
     * i) { if ((punteroAsig + i) >= asignatura.size()) { punteroAsig = 0; }
     * else if (punteroAsig + i < 0) { punteroAsig = asignatura.size() - 1; }
     * else { punteroAsig += i; } if(!asignatura.isEmpty())
     * this.refrescarLista(); }
     */
    public void moverLisAsig(int i) {
        punteroAsig += i;
        if ((punteroAsig + 1) == asignatura.size()) {
            jButton6.setEnabled(false);
        } else {
            jButton6.setEnabled(true);
        }
        if (punteroAsig - 1 < 0) {
            jButton7.setEnabled(false);
        } else {
            jButton7.setEnabled(true);
        }

        if (!asignatura.isEmpty()) {
            this.refrescarLista();
        }
    }

    /**
     * Metodo que refrescar el campo de texto de las asignaturas
     */
    private void refrescarLista() {
        ArrayList<Asignatura> asig = new ArrayList(asignatura);

        asigTex.setText(asig.get(punteroAsig).getNombre());
    }

    /**
     * Metodo que comprueba si estan todos los datos bien rellenados
     *
     * @return boolean de si todo esta bien rellenado
     */
    private boolean todoCorrecto() {
        boolean r = true;
        if (this.asigTex.getText().equalsIgnoreCase("") || asignatura.isEmpty()) {
            r = false;
        }
        return r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        asigTex = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cursoTex = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 200));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Nombre del curso:");

        asigTex.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        asigTex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        asigTex.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        asigTex.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        asigTex.setFocusable(false);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton3.setText("Añadir ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Asignaturas");

        jButton4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton4.setText("Modificar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cursoTex.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N

        jButton5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton5.setText("Eliminar");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(">");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("<");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cursoTex, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(asigTex, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoTex, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(asigTex, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton crear Curso
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!this.todoCorrecto()) {
            JOptionPane.showMessageDialog(null, "DEBE INSERTAR UN NOMBRE Y ALMENOS UNA ASIGNATURA", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            enviarCurso();
            this.setVisible(false);
            padre.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Boton añadir asignatura
     *
     * @param evt
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CrearAsignatura asi = new CrearAsignatura(this);
        asi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    /**
     * Boton cancelar para salir sin efectuar cambios
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * Boton modificar
     *
     * @param evt
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ArrayList<Asignatura> asig = new ArrayList(asignatura);
        CrearAsignatura asi = new CrearAsignatura(this, asig.get(punteroAsig).getClon());
        asi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        ArrayList<Asignatura> cop = new ArrayList(asignatura);
        asignatura.remove(cop.get(punteroAsig));
        if (asignatura.isEmpty()) {
            asigTex.setText("");
            jButton5.setEnabled(false);
            jButton4.setEnabled(false);
            punteroAsig -= 1;
        } else if ((punteroAsig + 1) >= asignatura.size() && punteroAsig != 0) {
            this.moverLisAsig(-1);
        } else {
            this.moverLisAsig(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        moverLisAsig(-1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        moverLisAsig(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private Principal padre; //Ventana padre de esta ventana
    private TreeSet<Asignatura> asignatura = new TreeSet(); //Lista de asignaturas
    private int punteroAsig = -1; //Puntero de la lista asignatura
    private boolean modificar = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asigTex;
    private javax.swing.JTextField cursoTex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
