/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import elementos.Asignatura;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class CrearAsignatura extends javax.swing.JFrame {

    /**
     * Constructor inicial
     */
    public CrearAsignatura() {
        initComponents();
    }

    /**
     * Constructor para crear una nueva asignatura
     *
     * @param cur = objeto desde el que se crea este objeto CrearAsignatura
     */
    public CrearAsignatura(CrearCurso cur) {
        this.principal = cur;
        initComponents();
    }

    /**
     * Constructor para modificar una asignatura
     *
     * @param cur = objeto (CrearCurso) desde el que se crea este objeto
     * CrearAsignatura ejemplo this
     * @param a = objeto (Asignatura) en la cual se quieren aplicar los cambios
     */
    public CrearAsignatura(CrearCurso cur, Asignatura a) {
        this.principal = cur;
        this.modifica = true;
        initComponents();
        rellenarCampos(a);
        jButton2.setText("Modificar");
    }

    /**
     * instancia de un objeto Asignatura
     *
     * @return La asignatura instanciada
     */
    private Asignatura crearAsignatura() {
        return new Asignatura(nombreTex.getText(), profesorTex.getText(), aulaTex.getText(), Double.parseDouble(horaTex.getText()), colores[menuColores.getSelectedIndex()], contacTex.getText());
    }

    /**
     * Metodo para inicializar los campos de texto con los datos de la
     * asignatura
     */
    private void rellenarCampos(Asignatura a) {
        int colorNum = 0;
        nombreTex.setText(a.getNombre());
        profesorTex.setText(a.getProfesor());
        aulaTex.setText(a.getAula());
        contacTex.setText(a.getContacto());
        horaTex.setText(Double.toString(a.getHorasSema()));
        for (int i = 0; i < colores.length; i++) {
            if (a.getColor().equals(colores[i])) {
                colorNum = i;
            }
        }
        menuColores.setSelectedIndex(colorNum);
    }

    /**
     * Metodo que comprueba si estan todos los datos bien rellenados
     *
     * @return boolean de si todo esta bien rellenado
     */
    private boolean todoCorrecto() {
        boolean r = true;
        if (nombreTex.getText().equalsIgnoreCase("") || profesorTex.getText().equalsIgnoreCase("")
                || aulaTex.getText().equalsIgnoreCase("") || horaTex.getText().equalsIgnoreCase("")
                || contacTex.getText().equalsIgnoreCase("")) {
            r = false;
        }
        return r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuColores = new javax.swing.JComboBox<>();
        aulaTex = new javax.swing.JTextField();
        profesorTex = new javax.swing.JTextField();
        horaTex = new javax.swing.JTextField();
        nombreTex = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        contacTex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Aula:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Horas semanales:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Color:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Profesor:");

        menuColores.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        menuColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Rojo ", "Verde", "Amarillo", "Naranja" }));

        aulaTex.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        aulaTex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aulaTexMouseClicked(evt);
            }
        });

        profesorTex.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        profesorTex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesorTexMouseClicked(evt);
            }
        });

        horaTex.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        horaTex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                horaTexMouseClicked(evt);
            }
        });

        nombreTex.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        nombreTex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTexMouseClicked(evt);
            }
        });
        nombreTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTexActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Contacto:");

        contacTex.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        contacTex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contacTexMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(contacTex))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(profesorTex))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(horaTex))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aulaTex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(nombreTex))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(menuColores, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTex, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesorTex, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aulaTex, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaTex, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contacTex, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuColores, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTexActionPerformed

    }//GEN-LAST:event_nombreTexActionPerformed
    /**
     * Boton crear Asignatura controla que todo este bien y envia el objeto
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (!todoCorrecto()) {
                JOptionPane.showMessageDialog(null, "DEBE RELLENAR TODOS LOS CAMPOS", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                principal.addAsignatura(crearAsignatura(), modifica);
                principal.setVisible(true);
                this.dispose();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "EL CAMPO HORAS DEBE SER UN NUMERO", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Boton cancelar salir de la ventana sin realizar ningun cambio
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombreTexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTexMouseClicked
        if (modifica) {
            nombreTex.setText("");
        }
    }//GEN-LAST:event_nombreTexMouseClicked

    private void profesorTexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesorTexMouseClicked
        if (modifica) {
            profesorTex.setText("");
        }
    }//GEN-LAST:event_profesorTexMouseClicked

    private void aulaTexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aulaTexMouseClicked
        if (modifica) {
            aulaTex.setText("");
        }    }//GEN-LAST:event_aulaTexMouseClicked

    private void horaTexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horaTexMouseClicked
        if (modifica) {
            horaTex.setText("");
        }    }//GEN-LAST:event_horaTexMouseClicked

    private void contacTexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contacTexMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contacTexMouseClicked

    private final Color colores[] = {Color.blue, Color.red, Color.green, Color.yellow, Color.ORANGE};
    private CrearCurso principal;
    private boolean modifica = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aulaTex;
    private javax.swing.JTextField contacTex;
    private javax.swing.JTextField horaTex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> menuColores;
    private javax.swing.JTextField nombreTex;
    private javax.swing.JTextField profesorTex;
    // End of variables declaration//GEN-END:variables
}
